import type { Metadata } from "next";
import { Montserrat, Open_Sans } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "../providers";
import { Navbar } from "@/components/base/navbar";

const monserrat = Montserrat({
    subsets: ["latin"],
    weight: ["100", "200", "300", "400", "500", "700", "600", "800", "900"],
});

// const openSans = Open_Sans({
//     subsets: ["latin"],
//     weight: ["300", "400", "500", "700", "600", "800"],
// });

export const metadata: Metadata = {
    title: "Portfolio | dev.paczesny",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark text-foreground bg-background h-full">
            <body
                style={monserrat.style}
                className="flex items-center justify-center min-h-screen"
            >
                <Providers
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}
                >
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
