import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "../providers";
import { Navbar } from "@/components/base/navbar";

const inter = Inter({
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Portfolio | dev.paczesny",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark text-foreground bg-background h-full">
            <body
                className={
                    inter.className +
                    "flex items-center justify-center min-h-screen"
                }
            >
                <Providers
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}
                >
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
