import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "../providers";
import { Navbar } from "@/components/base/navbar";

const poppins = Poppins({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Login | dev.paczesny",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body
                className={
                    poppins.className +
                    "flex items-center justify-center min-h-screen"
                }
            >
                <Providers
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}
                >
                    <Navbar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
