import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "@/app/providers";
import Sidebar from "@/components/dashboard/sidebar";
import SidebarMobile from "@/components/dashboard/sidebar-mobile";

const inter = Inter({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark text-foreground bg-background h-full">
            <body
                className={
                    inter.className +
                    "flex items-center justify-center min-h-screen overflow-hidden"
                }
            >
                <Providers
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}
                >
                    <section className="grid min-h-screen w-full md:grid-cols-[220px_1fr] lg:grid-cols-[280px_1fr]">
                        <Sidebar />
                        <div className="flex> flex-col">
                            <SidebarMobile />
                            <main className="flex flex-1 flex-col gap-4 lg:gap-6">
                                {children}
                            </main>
                        </div>
                    </section>
                </Providers>
            </body>
        </html>
    );
}
