import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";

import { Providers } from "@/app/providers";
import Sidebar from "@/components/dashboard/sidebar";

const inter = Inter({
    subsets: ["latin"],
    weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
    title: "Dashboard",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="dark text-foreground bg-background h-full">
            <body
                className={
                    inter.className +
                    "flex items-center justify-center min-h-screen overflow-hidden"
                }
            >
                <Providers
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange={false}
                >
                    <section className="flex flex-row items-center justify-evenly min-h-screen w-full">
                        <Sidebar />
                        {children}
                    </section>
                </Providers>
            </body>
        </html>
    );
}
